D4CHAT-33 chore: Add profile repository
D4Team/d4-chat pull request #34
Opened 2023-03-19 20:28 UTC by OlegKoshelev

2023-03-20 05:28 UTC, PatokovN requested changes

2023-03-20 05:28 UTC, PatokovN commented on src/main/scala/ru/d4team/chat/dao/PersonDAO.scala
> +  override def findPerson(name: String): Task[Option[Person]] = run {
I think, it would be better to find a person using his ID.

2023-03-22 20:43 UTC, AlekseiLitkovetc commented on build.sbt
> +//  "-Wunused",                   // Warn if something from check list is unused.
It's not a good idea to disable all warnings

It's better to add exceptions for quill. For example:
```scala
"-Wconf:msg=(Quoted|idiomContext@_)&cat=unused:s"
```

2023-03-22 20:43 UTC, AlekseiLitkovetc commented on src/main/scala/ru/d4team/chat/dao/PersonDAO.scala
> +  }.map(_.map(Person.fromRecord))
As an option, we can add additional method for list transformation:
```scala
def fromRecords(rs: List[PersonRecord]): List[Person] = rs.map(fromRecord)
```
And then simplify method:
```scala
run(schema).map(Person.fromRecords)
```

2023-04-01 10:38 UTC, closed without merging